// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/alfath-redesign/CleanPro.tsx": () => import("../components/mockups/alfath-redesign/CleanPro.tsx"),
  "./components/mockups/alfath-redesign/DarkCommand.tsx": () => import("../components/mockups/alfath-redesign/DarkCommand.tsx"),
  "./components/mockups/alfath-redesign/FreshFriendly.tsx": () => import("../components/mockups/alfath-redesign/FreshFriendly.tsx")
};
